-- Crear la tabla cliente
CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    correo VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Insertar datos iniciales
INSERT INTO cliente (nombre, correo) VALUES
('Juan Pérez', 'juan.perez@example.com'),
('María López', 'maria.lopez@example.com'),
('Carlos Martínez', 'carlos.martinez@example.com'),
('Jonathan Lopez', 'jonathan.lopez@example.com'),
('Jonathan Morales', 'jonathan.morales@example.com'),
('Cliente Prueba', 'cliente.prueba@example.com');

CREATE TABLE Producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(255) NOT NULL,
    precio Integer NOT NULL,
    stock Integer NOT NUll,
    PRIMARY KEY (id)
);

INSERT INTO Producto (nombre, precio, stock) VALUES
('Coca Cola', 1.50, 10),
('Amburquesa', 2.50, 20),
('Papas', 3.50, 30),
('Leche', 1.50, 10),
('Pan Dulce', 1.50, 10),
('Semita', 1.50, 230),
('Botella de Agua', 1.50, 10),
('Sillas', 1.50, 190),
('Lampara', 1.50, 180),
('Mesa', 1.50, 70),
('Laptop', 100.50, 50),
('Memorias USB', 15.50, 10),
('Lapiceros', 2.50, 10);